image: gradle:jre-alpine

# GRADLE_OPTS: Disable the Gradle daemon for Continuous Integration servers as
#   correctness is usually a priority over speed in CI environments.
# GRADLE_USER_HOME: redirect the gradle user home to cache the wrapper and
#   dependencies.
variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GRADLE_USER_HOME: "./.gradle"
    GRADLE_USER_HOME_A: "$PWD/.gradle"

# Default cache
cache:
  paths:
    - .gradle

before_script:
  - env

# We redirect the gradle user home using -g so that it caches the
# wrapper and dependencies.
# https://docs.gradle.org/current/userguide/gradle_command_line.html
#
# Unfortunately it also caches the build output so
# cleaning removes reminants of any cached builds.
# The assemble task actually builds the project.
# If it fails here, the tests can't run.
build:
  stage: build
  script:
    - ./gradlew clean assemble
  allow_failure: false

# Use the generated build output to run the tests.
test:
  stage: test
  script:
    - ./gradlew check
